config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
  validates :name, :cnpj, :address, presence: { message: "Você deve informar todos os dados da filial" }
  validates :name, uniqueness: { message: "Nome já esta em uso"}
  validates :cnpj, uniqueness: { message: "CNPJ já esta em uso"}
  validate :cnpj_must_be_valid

  private

  def cnpj_must_be_valid
    return if CNPJ.valid?(cnpj)
    errors.add(:cnpj, 'CNPJ não é valido')
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController

	def index
		@subsidiaries = Subsidiary.all
	end

	def show
		@subsidiary = Subsidiary.find(params[:id])
	end

  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.create(params_subsidiary)
    if @subsidiary.save
      redirect_to @subsidiary
    else
      @errors = filter_error
      render :new
    end
  end

  def edit
    @subsidiary = Subsidiary.find(params[:id])
  end

  def update
    @subsidiary = Subsidiary.find(params[:id])
    if @subsidiary.update(params_subsidiary)
      redirect_to @subsidiary
    else
      @errors = filter_error
      render :edit
    end
  end

  private

  def params_subsidiary
    params.require(:subsidiary).permit(:name, :cnpj, :address)
  end

  def filter_error
    @subsidiary.errors.messages.map{|attribure, message| message}.uniq
  end
end

app/views/subsidiaries/edit.html.erb
<% if @errors.present? %>
  <% @errors.each do |error| %>
    <p><%= error[0] %></p>
  <% end %>
<% end %>

<%= form_for @subsidiary do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :cnpj, 'CNPJ' %>
  <%= f.text_field :cnpj %>
  <%= f.label :address, 'Endereço' %>
  <%= f.text_field :address %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', subsidiaries_path %>

app/views/subsidiaries/index.html.erb
<% if @subsidiaries.empty? %>
  <h1>Nenhuma filial cadastrada</h1>
<% end %>

<%= link_to 'Cadastrar filial', new_subsidiary_path %>

<% @subsidiaries.each do |subsidiary| %>
  <h2><%= link_to subsidiary.name, subsidiary_path(subsidiary) %></h2>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/subsidiaries/new.html.erb
<% if @errors.present? %>
  <% @errors.each do |error| %>
    <p><%= error[0] %></p>
  <% end %>
<% end %>

<%= form_for @subsidiary do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :cnpj, 'CNPJ' %>
  <%= f.text_field :cnpj %>
  <%= f.label :address, 'Endereço' %>
  <%= f.text_field :address %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', subsidiaries_path %>

app/views/subsidiaries/show.html.erb
<%= @subsidiary.name %>
<%= @subsidiary.cnpj %>
<%= @subsidiary.address %>

<%= link_to 'Editar', edit_subsidiary_path(@subsidiary) %>
<%= link_to 'Voltar', subsidiaries_path %>