config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :rentals

  validates :name, :cpf, :email, presence: { message: "Você deve informar todos os dados do cliente" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :cpf_must_be_valid

  scope :search, ->(query) { where('name LIKE ?', "%#{query}%").or(where(cpf: query)) }

  private

  def cpf_must_be_valid
    return if CPF.valid?(cpf)
    errors.add(:cpf, 'CPF invalido')
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params_customer)
    if @customer.save
      redirect_to @customer
    else
      @errors = filter_error
      render 'new'
    end
  end

  def search
    @customers = Customer.search(params[:q])
    render 'index'
  end

  private

  def params_customer
    params.require(:customer).permit(:name, :cpf, :email)
  end

  def filter_error
    @customer.errors.messages.map{|attribure, message| message}.uniq
  end
end

app/views/customers/index.html.erb
<h1>Clientes</h1>

<% if @customers.empty? %>
  <h1>Nenhum cliente cadastrado</h1>
<% end %>

<%= form_with(url: search_customers_path, method: 'get') do |f| %>
  <%= f.label(:q, 'Busca') %>
  <%= f.search_field(:q) %>
  <%= f.submit "Buscar" %>
<% end%>

<%= link_to 'Cadastrar cliente', new_customer_path %>

<% @customers.each do |customer| %>
	<h2><%= link_to customer.name, customer_path(customer) %></h2>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/customers/new.html.erb
<% if @errors.present? %>
  <% @errors.each do |error| %>
    <p><%= error[0] %></p>
  <% end %>
<% end %>

<%= form_for @customer do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.label :cpf, 'CPF' %>
	<%= f.text_field :cpf %>
	<%= f.label :email, 'Email' %>
	<%= f.text_field :email %>
	<%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', customers_path %>

app/views/customers/show.html.erb
<h3>Detalhe do cliente</h3>

<dl>
  <dt>Nome do cliente:</dt>
  <dd><%= @customer.name %></dd>
  <dt>CPF do cliente:</dt>
  <dd><%= @customer.cpf %></dd>
  <dt>E-mail do cliente:</dt>
  <dd><%= @customer.email %></dd>
</dl>

<h3><%= Rental.model_name.human(count: 2) %></h3>

<table>
  <tr>
    <th><%= Rental.human_attribute_name(:code) %></th>
    <th><%= Rental.human_attribute_name(:start_date) %></th>
    <th><%= Rental.human_attribute_name(:end_date) %></th>
    <th><%= Rental.human_attribute_name(:car_category) %></th>
    <th><%= Rental.human_attribute_name(:status) %></th>
    <th>Ações</th>
  </tr>
  <% @customer.rentals.each do |rental| %>
    <tr id="rental-<%= rental.code %>">
      <td><%= rental.code %></td>
      <td><%= l rental.start_date %></td>
      <td><%= l rental.end_date %></td>
      <td><%= rental.car_category.name %></td>
      <td><%= Rental.human_attribute_name("status.#{rental.status}") %></td>
      <td>
        <% if rental.scheduled? %>
          <%= link_to 'Iniciar', new_rental_car_rental_path(rental) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Voltar', customers_path %>