config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :rentals
  has_many :cars, through: :car_models

  validates :name, :daily_rate, :car_insurance, 
            :third_party_insurance, presence: 
            { message: "Você deve informar todos os dados da categoria" }
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController

  def index
    @carcategories = CarCategory.all
  end

  def new
    @carcategory = CarCategory.new
  end

  def create
    @carcategory = CarCategory.new(params_car_category)
    if @carcategory.save
      redirect_to @carcategory
    else
      @errors = filter_error
      render :new
    end
  end

  def show
    @carcategory = CarCategory.find(params[:id])
  end

  private

  def params_car_category
    params.require(:car_category).permit(:name, :daily_rate, :car_insurance, :third_party_insurance)
  end

  def filter_error
    @carcategory.errors.messages.map{|attribure, message| message}.uniq
  end
end

app/views/car_categories/index.html.erb
<h1>Categorias de carrors</h1>

<% if @carcategories.empty? %>
  <h2>Nenhuma categoria cadastrada</h2>
<% end %>

<%= link_to 'Cadastrar categoria', new_car_category_path %>

<% @carcategories.each do |category| %>
  <div>
  <h1><%= link_to "Categoria #{category.name}", category %></h1>
    <dl>
      <dt>Diaria</dt>
      <dd><%= number_to_currency(category.daily_rate) %></dd>
    </dl>
  </div>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/car_categories/new.html.erb
<% if @errors.present? %>
  <% @errors.each do |error| %>
    <p><%= error[0] %></p>
  <% end %>
<% end %>

<%= form_for @carcategory do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :daily_rate, 'Taxa diaria' %>
  <%= f.number_field :daily_rate %>
  <%= f.label :car_insurance, 'Seguro do automóvel' %>
  <%= f.number_field :car_insurance %>
  <%= f.label :third_party_insurance, 'Seguro de terceiros' %>
  <%= f.number_field :third_party_insurance %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', car_categories_path %>

app/views/car_categories/show.html.erb
<section>
  <header>
    <h1>Categoria <%= @carcategory.name %></h1>
  </header>
  <dl>
    <dt>Diaria</dt>
    <dd><%= number_to_currency(@carcategory.daily_rate) %></dd>
    <dt>Seguro do carro</dt>
    <dd><%= number_to_currency(@carcategory.car_insurance) %></dd>
    <dt>Seguro de terceiros</dt>
    <dd><%= number_to_currency(@carcategory.third_party_insurance) %></dd>
  </dl>

  <h3>Modelos de carro</h3>
  <% @carcategory.car_models.each do |car_model| %>
    <li>
      <%= link_to car_model.name, car_model %>
    </li>
  <% end %>
</section>

<%= link_to 'Voltar', car_categories_path %>