config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_categories, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :customer
  belongs_to :car_category
  has_one :car_rental
  has_one :car, through: :car_rental

  validates :start_date, :end_date, presence: true

  before_create :generate_code

  enum status: { scheduled: 0, ongoing: 5 }

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(6).upcase
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]

  def index
    @rentals = Rental.all
  end

  def show
    set_rental
  end

  def new
    @rental = Rental.new
    @customers = Customer.all
    @car_categories = CarCategory.all
  end

  def create
    @rental = Rental.new(params_rental)
    if @rental.save
      redirect_to @rental
    else
      @customers = Customer.all
      @car_categories = CarCategory.all
      render 'new'
    end
  end

  def search
    @q = params[:q]
    @rentals = Rental.all
    @rental = Rental.find_by(code: @q.upcase)
    if @q.blank?
      flash.now[:alert] = 'Busca não pode ficar em branco'
      render 'index'
    elsif @rental.blank?
      flash.now[:alert] = "Nenhum código foi em contrado para: #{@q}"
      render 'index'
    else
      render 'show'
    end
  end
  
  private

  def params_rental
    params.require(:rental).permit(:start_date, :end_date, :customer_id, :car_category_id)
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/views/rentals/index.html.erb
<h1>Locações</h1>

<%= link_to 'Cadastrar locação', new_rental_path %>

<%= form_with url: search_rentals_path, method: "get", local: true do |f| %>
  <%= f.label :q, 'Código' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Data de início</th>
      <th>Data de término</th>
      <th>Cliente</th>
      <th>Categoria</th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr id="rental-<%= rental.id %>">
        <td><%= rental.start_date %></td>
        <td><%= rental.end_date %></td>
        <td><%= rental.customer.name %></td>
        <td><%= rental.car_category.name %></td>
        <th><%= link_to 'Ver detalhes', rental %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rentals/new.html.erb
<h1>Nova Locação</h1>

<% @rental.errors.full_messages.each do |error| %>
  <ul>
    <%= error %>
  </ul>
<% end %>

<%= form_with(model: @rental, local: true) do |f| %>
  <%= f.label :start_date, 'Data de início' %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date, 'Data de término' %>
  <%= f.date_field :end_date %>
  <%= f.label :customer_id, 'Cliente' %>
  <%= f.collection_select(:customer_id, @customers, :id, :name) %>
  <%= f.label :car_category_id, 'Categoria' %>
  <%= f.collection_select(:car_category_id, @car_categories, :id, :name) %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/rentals/show.html.erb
<h1>Detalhe da locação</h1>

<dl>
  <dd>Código: </dd>
  <dt><%= @rental.code %></dt>
  <dd>Data de início: </dd>
  <dt><%= l @rental.start_date %></dt>
  <dd>Data de término: </dd>
  <dt><%= l @rental.end_date %></dt>
  <dd>Cliente: </dd>
  <dt><%= @rental.customer.name %></dt>
  <dd>Categoria: </dd>
  <dt><%= @rental.car_category.name %></dt>
  <%= link_to 'Iniciar', new_rental_car_rental_path(@rental) %>
</dl>

<% if @rental.car_rental.present? %>
  <h1>Iniciado</h1>
  <dl>
    <dd>Data de inicio: </dd>
    <dt><%= I18n.l Time.now, format: :long %></dt>
    <dd>Placa do carro: </dd>
    <dt><%= @rental.car_rental.car.license_plate %></dt>
    <dd>Locação iniciada por: </dd>
    <dt><%= @rental.car_rental.user.email %></dt>
    <dd>Status: </dd>
    <dt><%= Rental.human_attribute_name("status.#{@rental.status}") %></dt>
  </dl>
<% end %>